### ISSUE TITLE
Any plan for null safety support?

### ISSUE THREAD

**Issue by sowens-csd** [csongorkeller/flutter_open_weather_package#1]

**Comment by csongorkeller** [comment]
Hey @sowens-csd 
Yeah, I'm planning to do it sometime. Hopefully in a couple of weeks. 
But any PR is more than welcome if you want to contribute 🙂
Cheerio

**Comment by sowens-csd** [comment]
Thanks for the quick response, and for letting me now you're open to a PR. I've done a couple of my own plugins recently.  If the timing works out I'll have a look at converting this one.

**Comment by csongorkeller** [comment]
Great @sowens-csd 
Looking forward receiving your PR. 
Have a nice weekend

**Comment by csongorkeller** [comment]
Hi @sowens-csd ,
Is the PR still on the horizon? Are you planning to make some time? Or can I close the issue?

**Comment by sowens-csd** [comment]
Yes, you can close it, or at least I no longer need it. Sorry I should have posted.

**Comment by csongorkeller** [comment]
Hi @sowens-csd 
Just thought to let you know that the plugin is null-safe now. And also supports flutter 3.x.x.
Have fun and feel free to contribute if you want :)
