### ISSUE TITLE
Please update package for null-safety and Flutter 3.x

### ISSUE THREAD

**Issue by gslender** [csongorkeller/flutter_open_weather_package#3]
Hi,

I've updated the package for null-safety and Flutter 3.x on my Fork of your repo (https://github.com/gslender/flutter_open_weather_package), so if you can copy/reflect those same changes and republish that would be great, or alternatively, I'll just publish a package derivative if you're too busy or not interested in maintaining.

Thanks

**Comment by gslender** [comment]
I also updated the package to respect the advice from Flutter Lints

**Comment by csongorkeller** [comment]
Hi @gslender ,
Thanks for the update. I'll add it to the package and make a new release soon.
If there is anything else you'd want to add feel free to make a PR.

Cheers

**Comment by gslender** [comment]
Awesome, if you're active then yes I'll send PRs from here onwards once the new null-safety release is published

**Comment by csongorkeller** [comment]
Great, will let you know once the update is out.

**Comment by gslender** [comment]
How you going? I'd like to add the official weather conditions as a class object and I'm resisting the urge to added to my fork and wait and do a PR etc... but if you're too busy I can just create a new package derivative and outline you as the original author... I'd probably just post it on pub.dev as null_safe_open_weather_client

**Comment by csongorkeller** [comment]
Hey man,
Expect the update by the end of today. 
Almost done with it.

**Comment by csongorkeller** [comment]
Hey man,
the update is done: https://pub.dev/packages/open_weather_client
Enjoy and thanks for the contributionss. Feel free to send the PRs.
