### ISSUE TITLE
Error when package is deserializing

### ISSUE THREAD

**Issue by mrx12335** [csongorkeller/flutter_open_weather_package#4]
Implemented the package like in the tutorial amd i got the exception "Expected a value of type 'Map<dynamic, dynamic>', but got one of type 'Null'.

Got it at '.catchError((err) => print(err));' and the error happens in the package you wrote

**Comment by csongorkeller** [comment]
Thanks @mrx12335 for reporting the issue. Can you provide some details on what part actually causes the issue for you?

**Comment by mrx12335** [comment]
Currently not at work but i think its the deserializer because i can send and receive the request but then your library throws the error. What I've tried to use is the five day forecast with coordinates and then city name. On the latest version

**Comment by csongorkeller** [comment]
@mrx12335 I was able to reproduce the issue. There will be a fix soon. Thanks for reporting it

**Comment by Feichtmeier** [comment]
Having the same issue :crying_cat_face: 

I think the forecast does not have the coord property

**Comment by csongorkeller** [comment]
Many thanks @Feichtmeier for the PR. Will review it today in the evening and merge it if all works.
Thanks for the work

**Comment by Feichtmeier** [comment]
Yw! Thanks for this package

**Comment by csongorkeller** [comment]
The PR is merged, thanks @Feichtmeier for the collaboration. v.2.1 is also pushed to pub.dev: https://pub.dev/packages/open_weather_client/versions/2.1.0
