### ISSUE TITLE
Support different languages

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [csongorkeller/flutter_open_weather_package#6]
The API supports differente languages.
Is there any plan to support it in the library as well?

**Comment by csongorkeller** [comment]
Hi @mariomurrent-softwaresolutions ,
Yes. It's deff planned. I didn't have time yet to implement it. Any PR is welcome

**Comment by mariomurrent-softwaresolutions** [comment]
Sounds good - if I have time ill have a look at it :)

**Comment by csongorkeller** [comment]
Issue closed, new version released. Thanks @mariomurrent-softwaresolutions for the PR.
https://pub.dev/packages/open_weather_client/versions/2.2.0

**Comment by mariomurrent-softwaresolutions** [comment]
Thx 😊
