### ISSUE TITLE
Support for styling

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [csongorkeller/flutter_open_weather_package#8]
It would be nice to have some support for styling: e.g.: Change font size etc.

**Comment by csongorkeller** [comment]
Hi @mariomurrent-softwaresolutions 

Thanks for the suggestion. Can you elaborate a bit on how you imagine the styling part?

Because technically, if you don't use the already build widgets but the functions the package provides you have full control over styling anything.

**Comment by csongorkeller** [comment]
Hi @mariomurrent-softwaresolutions 

Thanks for the suggestion. Can you elaborate a bit on how you imagine the styling part?

Because technically, if you don't use the already build widgets but the functions the package provides you have full control over styling anything.

**Comment by mariomurrent-softwaresolutions** [comment]
Ah well, yeah I could use the functions. You are totally right. Sorry
